### ISSUE TITLE
Typescript definitions not up to date

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/node-tree-sitter#42] opened 2019-04-29 19:48 UTC
The type definitions seem to miss some functions. https://github.com/tree-sitter/node-tree-sitter/blob/master/tree-sitter.d.ts

https://github.com/tree-sitter/node-tree-sitter/blob/master/src/parser.h

For e.g. ParseTextBuffer is missing.

**Comment by maxbrunsfeld** [comment] 2019-04-29 19:50
I think this is a duplicate of #32.

**Closed by maxbrunsfeld** 2019-04-29 19:50 UTC
Labels: bug
