### ISSUE TITLE
unable to install tree-sitter using node v19.0.1

### ISSUE THREAD

**Issue by jonas2811** [tree-sitter/node-tree-sitter#119] opened 2022-11-17 10:27 UTC
Hey guys so i basically only tried the command: npm install tree-sitter  (like described in the readme.md) and i get some errors:

npm install tree-sitter
npm ERR! code 1
npm ERR! path /home/jonas/d/node_modules/tree-sitter
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! make: Entering directory '/home/jonas/d/node_modules/tree-sitter/build'
npm ERR!   CC(target) Release/obj.target/tree_sitter/vendor/tree-sitter/lib/src/lib.o
npm ERR! rm -f Release/obj.target/tree_sitter.a Release/obj.target/tree_sitter.a.ar-file-list; mkdir -p `dirname Release/obj.target/tree_sitter.a`
npm ERR! ar crs Release/obj.target/tree_sitter.a @Release/obj.target/tree_sitter.a.ar-file-list
npm ERR!   COPY Release/tree_sitter.a
npm ERR!   CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/binding.o
npm ERR!   CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/conversions.o
npm ERR!   CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/language.o
npm ERR!   CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/logger.o
npm ERR! make: Leaving directory '/home/jonas/d/node_modules/tree-sitter/build'
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=19.0.1 runtime=node arch=x64 libc= platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.0.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jonas/d/node_modules/tree-sitter/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jonas/.cache/node-gyp/19.0.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/jonas/.cache/node-gyp/19.0.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/jonas/.cache/node-gyp/19.0.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/jonas/d/node_modules/tree-sitter',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/binding.cc:1:
npm ERR! /home/jonas/.cache/node-gyp/19.0.1/include/node/node.h:976:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!   976 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |                                           ^
npm ERR! /home/jonas/.cache/node-gyp/19.0.1/include/node/node.h:1010:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!  1010 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../src/binding.cc:25:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!    25 | NODE_MODULE(tree_sitter_runtime_binding, InitAll)
npm ERR!       | ^~~~~~~~~~~
npm ERR! ../src/logger.cc: In static member function ‘static void node_tree_sitter::Logger::Log(void*, TSLogType, const char*)’:
npm ERR! ../src/logger.cc:44:21: error: ‘class v8::Function’ has no member named ‘CreationContext’; did you mean ‘GetCreationContext’?
npm ERR!    44 |   Nan::Call(fn, fn->CreationContext()->Global(), 3, argv);
npm ERR!       |                     ^~~~~~~~~~~~~~~
npm ERR!       |                     GetCreationContext
npm ERR! ../src/logger.cc:51:62: error: ‘class v8::Function’ has no member named ‘CreationContext’; did you mean ‘GetCreationContext’?
npm ERR!    51 |     Local<Object> console = Local<Object>::Cast(Nan::Get(fn->CreationContext()->Global(), Nan::New("console").ToLocalChecked()).ToLocalChecked());
npm ERR!       |                                                              ^~~~~~~~~~~~~~~
npm ERR!       |                                                              GetCreationContext
npm ERR! make: *** [tree_sitter_runtime_binding.target.mk:131: Release/obj.target/tree_sitter_runtime_binding/src/logger.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 5.15.0-52-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/jonas/d/node_modules/tree-sitter
npm ERR! gyp ERR! node -v v19.0.1
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jonas/.npm/_logs/2022-11-17T09_55_23_334Z-debug-0.log
jonas@jonas-Lenovo-Yoga-C740-14IML:~/d$ npm install tree-sitter
npm ERR! code 1
npm ERR! path /home/jonas/d/node_modules/tree-sitter
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! make: Entering directory '/home/jonas/d/node_modules/tree-sitter/build'
npm ERR!   CC(target) Release/obj.target/tree_sitter/vendor/tree-sitter/lib/src/lib.o
npm ERR! rm -f Release/obj.target/tree_sitter.a Release/obj.target/tree_sitter.a.ar-file-list; mkdir -p `dirname Release/obj.target/tree_sitter.a`
npm ERR! ar crs Release/obj.target/tree_sitter.a @Release/obj.target/tree_sitter.a.ar-file-list
npm ERR!   COPY Release/tree_sitter.a
npm ERR!   CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/binding.o
npm ERR!   CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/conversions.o
npm ERR!   CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/language.o
npm ERR!   CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/logger.o
npm ERR! make: Leaving directory '/home/jonas/d/node_modules/tree-sitter/build'
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=19.0.1 runtime=node arch=x64 libc= platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.0.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jonas/d/node_modules/tree-sitter/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jonas/.cache/node-gyp/19.0.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/jonas/.cache/node-gyp/19.0.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/jonas/.cache/node-gyp/19.0.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/jonas/d/node_modules/tree-sitter',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/binding.cc:1:
npm ERR! /home/jonas/.cache/node-gyp/19.0.1/include/node/node.h:976:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!   976 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |                                           ^
npm ERR! /home/jonas/.cache/node-gyp/19.0.1/include/node/node.h:1010:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!  1010 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../src/binding.cc:25:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!    25 | NODE_MODULE(tree_sitter_runtime_binding, InitAll)
npm ERR!       | ^~~~~~~~~~~
npm ERR! ../src/logger.cc: In static member function ‘static void node_tree_sitter::Logger::Log(void*, TSLogType, const char*)’:
npm ERR! ../src/logger.cc:44:21: error: ‘class v8::Function’ has no member named ‘CreationContext’; did you mean ‘GetCreationContext’?
npm ERR!    44 |   Nan::Call(fn, fn->CreationContext()->Global(), 3, argv);
npm ERR!       |                     ^~~~~~~~~~~~~~~
npm ERR!       |                     GetCreationContext
npm ERR! ../src/logger.cc:51:62: error: ‘class v8::Function’ has no member named ‘CreationContext’; did you mean ‘GetCreationContext’?
npm ERR!    51 |     Local<Object> console = Local<Object>::Cast(Nan::Get(fn->CreationContext()->Global(), Nan::New("console").ToLocalChecked()).ToLocalChecked());
npm ERR!       |                                                              ^~~~~~~~~~~~~~~
npm ERR!       |                                                              GetCreationContext
npm ERR! make: *** [tree_sitter_runtime_binding.target.mk:131: Release/obj.target/tree_sitter_runtime_binding/src/logger.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 5.15.0-52-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/jonas/d/node_modules/tree-sitter
npm ERR! gyp ERR! node -v v19.0.1
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:

**Comment by razzeee** [comment] 2022-11-17 11:12
Basically a duplicate of https://github.com/tree-sitter/node-tree-sitter/issues/106

**Closed** 2022-11-18 16:59 UTC

**Comment by milahu** [comment] 2022-12-21 16:14
> Basically a duplicate of #106

no ...

`npm install tree-sitter` works on node 18

`npm install tree-sitter` fails on node 19 with

> `../src/logger.cc:44:21: error: ‘class v8::Function’ has no member named ‘CreationContext’; did you mean ‘GetCreationContext’?`

```sh
cd $(mktemp -d)
npm init -y 
node --version # v19.0.0
pnpm i tree-sitter tree-sitter-bash
# error: ‘class v8::Function’ has no member named ‘CreationContext’

nix-shell -p nodejs-18_x # switch to node 18
node --version # v18.12.0
rm -rf node_modules/
pnpm i tree-sitter tree-sitter-bash # ok

cat >index.mjs <<'EOF'
import TreeSitter from "tree-sitter"
import TreeSitterBash from "tree-sitter-bash"
const parser = new TreeSitter()
parser.setLanguage(TreeSitterBash)
const sourceCode = 'asdf'
const tree = parser.parse(sourceCode)
console.dir(tree)
EOF
node index.mjs # ok

cat node_modules/tree-sitter/package.json | jq -r .version # 0.20.1
cat node_modules/tree-sitter-bash/package.json | jq -r .version # 0.19.0
```

**Comment by SamStenner** [comment] 2023-01-19 05:14
Same issue

**Comment by richardTowers** [comment] 2023-02-19 16:09
Also having the same issue, reproducible in a blank GitHub Codespace. Works in node 18, fails in node 19.

Debug log from the build shows the same issue as the original report: [debug.log](https://github.com/tree-sitter/node-tree-sitter/files/10777345/debug.log)

```
486 error ../src/logger.cc:44:21: error: ‘class v8::Function’ has no member named ‘CreationContext’; did you mean ‘GetCreationContext’?
486 error    44 |   Nan::Call(fn, fn->CreationContext()->Global(), 3, argv);
486 error       |                     ^~~~~~~~~~~~~~~
486 error       |                     GetCreationContext
486 error ../src/logger.cc:51:62: error: ‘class v8::Function’ has no member named ‘CreationContext’; did you mean ‘GetCreationContext’?
486 error    51 |     Local<Object> console = Local<Object>::Cast(Nan::Get(fn->CreationContext()->Global(), Nan::New("console").ToLocalChecked()).ToLocalChecked());
486 error       |                                                              ^~~~~~~~~~~~~~~
486 error       |                                                              GetCreationContext
486 error make: *** [tree_sitter_runtime_binding.target.mk:131: Release/obj.target/tree_sitter_runtime_binding/src/logger.o] Error 1
486 error gyp ERR! build error 
486 error gyp ERR! stack Error: `make` failed with exit code: 2
```
