### ISSUE TITLE
Module not found Error

### ISSUE THREAD

**Issue by goneXII** [tree-sitter/node-tree-sitter#153] opened 2023-06-25 09:16 UTC
I got these errors when i tried to install "tree-sitter" and "tree-sitter-javascript"

`Module not found: Error: Can't resolve '../../build/Debug/tree_sitter_javascript_binding'

 warning  in ./node_modules/tree-sitter-javascript/bindings/node/index.js

Module not found: Error: Can't resolve '../../build/Release/tree_sitter_javascript_binding'

 warning  in ./node_modules/tree-sitter/index.js

Module not found: Error: Can't resolve './build/Debug/tree_sitter_runtime_binding' 

 warning  in ./node_modules/tree-sitter/index.js`

**Comment by verhovsky** [comment] 2023-06-25 11:20
Duplicate of #122

**Closed by verhovsky** 2023-06-25 11:20 UTC
